### ISSUE TITLE
Loading firmware from web app

### ISSUE THREAD

**Issue by TimNe0** [emfcamp/badge-2024-software#102]
the instructions seem unclear.  This is how I have had success

Open "Edge" / IE (may work on Chrome, but I use firefox normally)
goto web firmware page
click connect
connect device with USB, keep boop/bat held down, hit reboop, wait for it to read "USB JTAG/serial debug unit" instead of "Espressif CDC Device"
You can now release the boop/bat.

Now hit the final connect button, should connect.

**Comment by npentrel** [comment]
I think you were referring to https://github.com/emfcamp/badge-2024-software/blob/main/flasher/index.html which I think has been fixed so I will close this, please reopen this ticket if that's wrong. Thanks!
