### ISSUE TITLE
Cannot install apps consecutively from the store

### ISSUE THREAD

**Issue by npentrel** [emfcamp/badge-2024-software#120]
1. Open app store
2. Open StoreInstall
3. Install an app
4. Try to go back to StoreInstall (doesn't always work - can't press down sometimes)
5. Try to select another app (doesn't work - can't press down)

**Comment by andypiper** [comment]
Yes, I noticed the same thing - should this be logged on the [app store repo](https://github.com/emfcamp/badge-2024-app-store)? I guess that is the backend, and the on-badge code is here?

**Comment by npentrel** [comment]
Reasonably sure it's a software issue. My guess is something with menus or handlers not being set correctly is my guess but I haven't looked into it

**Comment by Gregox273** [comment]
Looking at `app_store.py`, it looks like the `available_menu` is cleaned up but not destroyed when selecting an app to install, so the button down event handler is removed during cleanup but then never re-registered.

Presumably the `Menu` instance in `AppStoreApp.available_menu` ought to be replaced when navigating back round? Or destroyed right after cleanup when an app is selected.
