### ISSUE TITLE
Calling wifi.get_ip throws

### ISSUE THREAD

**Issue by hughrawlinson** [emfcamp/badge-2024-software#37]
Seems like the API doesn't quite line up somewhere. This is after confirming that `wifi.isconnected()` returns true (which is weird because I'm very unsure how the badge would connect to our wifi, I would expect it to return false)

```
  File "/home/hugh/Development/github.com/emfcamp/badge-2024-software/modules/wifi.py", line 191, in ifconfig
    return _STA_IF.ifconfig()
AttributeError: 'WLAN' object has no attribute 'ifconfig'. Did you mean: 'config'?
```

**Comment by sknebel** [comment]
works right now (with current firmware, in the actual field). If not connected, `None` is returned.

**Comment by andypiper** [comment]
I think this can now be closed?

**Comment by npentrel** [comment]
> I think this can now be closed? (happy to support issue triage/labelling if the team would like help on that)

I just started doing that @andypiper - please feel free to as well though!

**Comment by npentrel** [comment]
This no longer throws, if the issue recurs we can open a new issue.
