### ISSUE TITLE
Hexpansion EEPROMs

### ISSUE THREAD

**Issue by Skyler84** [emfcamp/badge-2024-software#4]
so the general idea is that hexpansions can have an I2C eeprom which allows easy identification of hardware and has potential for storing state/code directly in them. 

The main feature that's going to be needed is really the identification, as telling what hexpansion is inserted and therefore what code can run it without breaking anything is most important. 
Additionally it would be nice if we could store code and state on the eeprom but i think that's less necessary if the app store is functional. 

for identification, potentially some TLV metadata or similar could be used to encode data such as hardware revision, hardware id, creator, hexpansion name and other details (should probably be checksummed and have a magic to make sure we're not reading garbage if users do their own thing with the eeprom). 

any other ideas related to this feel free to comment here!

**Comment by Skyler84** [comment]
https://github.com/raspberrypi/hats
Looks like a good point to start from? has well defined structure already!

**Comment by kliment** [comment]
The spec closest to what we want to do is the format of https://badge.team/docs/standards/sao/ but we'll need some more things. For organizational reasons we'll need a vendor identifier and device identifier (at least two bytes each) and we'll need to support multiple EEPROM models that have different addresses, so not only 0x50. So we'll likely have a header similar to the binary SAO header, and then a filesystem following that.

**Comment by b0xcat** [comment]
There's a basic implementation of this, including having apps on hexpansion eeproms in #9! No checksum though, maybe that would be good to add still?

**Comment by thinkl33t** [comment]
This is all working
