### ISSUE TITLE
M24C16-RMN6TP in approved EEPROM list, but addressing appears incorrect

### ISSUE THREAD

**Issue by gsuberland** [emfcamp/badge-2024-software#75]
The M24C16-RMN6TP is in the list of approved EEPROMs [here](https://tildagon.badge.emfcamp.org/hexpansions/creating-hexpansions/).

The [datasheet](https://www.st.com/en/memories/m24c16-r.html) shows that the M24C16-R series of EEPROMs uses the address format `0b1010xxxx`, with the bottom bits used for page select and R/W.

![image](https://github.com/emfcamp/badge-2024-software/assets/6430604/8ccdc31e-984b-428d-9afc-b002576d5a6e)

This means that the base address of this EEPROM series is **0xA0**.

However, the badge firmware uses 0x50 or 0x57 for addressing EEPROMs:

https://github.com/emfcamp/badge-2024-software/blob/e8d716ad249e77833d2ef2865fb29c304a85203c/modules/system/hexpansion/util.py#L9-L15

As such, unless I am missing something critical, it is not possible for any hexpansions which use the M24C16-R series EEPROMs to be detected and read from with the current firmware.

**Comment by BartDeWaal** [comment]
The rightmost bit is R/W, so it doesn't count for the address. So you need to shift the address right by 1.

That means the address is 1010000, so 0x50. This is correct.

**Comment by hairymnstr** [comment]
There are certainly issues with this EEPROM which need addressing, see #129. However, I am certain that addressing is not the issue so I'm going to close this particular issue.

**Comment by gsuberland** [comment]
No worries, it does seem that the address thing was a red herring.
