### ISSUE TITLE
Battery level incorrect

### ISSUE THREAD

**Issue by ChrisDick** [emfcamp/badge-2024-software#83]
Battery Level incorrect. min and max voltage incorrect, Charge current could be used during charge to improve accuracy.

**Comment by npentrel** [comment]
Is this still the case? My badge is no longer displaying above 100% charge levels...

**Comment by ChrisDick** [comment]
yes, the power.BatteryLevel() is still returning higher than 100%. The battery meter app clamps it to 100%. Testing a fix now.

**Comment by ChrisDick** [comment]
fixed in PR #179
