### ISSUE TITLE
Setting LED Colour conflicts with firmware results in flashing

### ISSUE THREAD

**Issue by pixelscript** [emfcamp/badge-2024-software#88]
**Steps:** 

Set led colour to black using:

```
for i in range(0,12):
  tildagonos.leds[i+1] = (0, 0, 0)
```

Have some work processing in same `update` loop

**Result:**

LEDs will flash as it seems the firmware is wanting to write the rainbow colours every step

**Expected:**

LEDs to remain off.

Maybe I'm missing some setting? Thanks!!

**Comment by thinkl33t** [comment]
you need to send a PatternDisable event to prevent the system pattern generator from running.

then send a PatternEnable event to turn it back on

**Comment by pixelscript** [comment]
That was quick, legend thank you!
